"use strict";var _library=!1;function createCommonjsModule(e,t){return t={exports:{}},e(t,t.exports),t.exports}var _global=createCommonjsModule(function(e){// https://github.com/zloirock/core-js/issues/86#issuecomment-115759028
var t=e.exports="undefined"!=typeof window&&window.Math==Math?window:"undefined"!=typeof self&&self.Math==Math?self// eslint-disable-next-line no-new-func
:Function("return this")();"number"==typeof __g&&(__g=t)}),_aFunction=function(e){if("function"!=typeof e)throw TypeError(e+" is not a function!");return e},_ctx=function(e,t,o){return(_aFunction(e),void 0===t)?e:1===o?function(o){return e.call(t,o)}:2===o?function(o,r){return e.call(t,o,r)}:3===o?function(o,r,n){return e.call(t,o,r,n)}:function()/* ...args */{return e.apply(t,arguments)}},toString={}.toString,_cof=function(e){return toString.call(e).slice(8,-1)},_core=createCommonjsModule(function(e){var t=e.exports={version:"2.5.7"};"number"==typeof __e&&(__e=t)}),_core_1=_core.version,_shared=createCommonjsModule(function(e){var t=_global["__core-js_shared__"]||(_global["__core-js_shared__"]={});(e.exports=function(e,o){return t[e]||(t[e]=o===void 0?{}:o)})("versions",[]).push({version:_core.version,mode:"global",copyright:"\xA9 2018 Denis Pushkarev (zloirock.ru)"})}),id=0,px=Math.random(),_uid=function(e){return"Symbol(".concat(e===void 0?"":e,")_",(++id+px).toString(36))},_wks=createCommonjsModule(function(e){var t=_shared("wks"),o=_global.Symbol,r="function"==typeof o,n=e.exports=function(e){return t[e]||(t[e]=r&&o[e]||(r?o:_uid)("Symbol."+e))};n.store=t}),TAG=_wks("toStringTag"),ARG="Arguments"==_cof(function(){return arguments}()),tryGet=function(e,t){try{return e[t]}catch(t){/* empty */}},_classof=function(e){var t,o,r;return e===void 0?"Undefined":null===e?"Null"// @@toStringTag case
:"string"==typeof(o=tryGet(t=Object(e),TAG))?o// builtinTag case
:ARG?_cof(t)// ES3 arguments fallback
:"Object"==(r=_cof(t))&&"function"==typeof t.callee?"Arguments":r},_isObject=function(e){return"object"==typeof e?null!==e:"function"==typeof e},_anObject=function(e){if(!_isObject(e))throw TypeError(e+" is not an object!");return e},_fails=function(e){try{return!!e()}catch(t){return!0}},_descriptors=!_fails(function(){return 7!=Object.defineProperty({},"a",{get:function(){return 7}}).a}),document$1=_global.document,is=_isObject(document$1)&&_isObject(document$1.createElement),_domCreate=function(e){return is?document$1.createElement(e):{}},_ie8DomDefine=!_descriptors&&!_fails(function(){return 7!=Object.defineProperty(_domCreate("div"),"a",{get:function(){return 7}}).a}),_toPrimitive=function(e,t){if(!_isObject(e))return e;var o,r;if(t&&"function"==typeof(o=e.toString)&&!_isObject(r=o.call(e)))return r;if("function"==typeof(o=e.valueOf)&&!_isObject(r=o.call(e)))return r;if(!t&&"function"==typeof(o=e.toString)&&!_isObject(r=o.call(e)))return r;throw TypeError("Can't convert object to primitive value")},dP=Object.defineProperty,f=_descriptors?Object.defineProperty:function(e,t,o){if(_anObject(e),t=_toPrimitive(t,!0),_anObject(o),_ie8DomDefine)try{return dP(e,t,o)}catch(t){/* empty */}if("get"in o||"set"in o)throw TypeError("Accessors not supported!");return"value"in o&&(e[t]=o.value),e},_objectDp={f:f},_propertyDesc=function(e,t){return{enumerable:!(1&e),configurable:!(2&e),writable:!(4&e),value:t}},_hide=_descriptors?function(e,t,o){return _objectDp.f(e,t,_propertyDesc(1,o))}:function(e,t,o){return e[t]=o,e},hasOwnProperty={}.hasOwnProperty,_has=function(e,t){return hasOwnProperty.call(e,t)},_redefine=createCommonjsModule(function(e){var t=_uid("src"),o="toString",r=Function[o],n=(""+r).split(o);_core.inspectSource=function(e){return r.call(e)},(e.exports=function(e,o,r,a){var i="function"==typeof r;i&&(_has(r,"name")||_hide(r,"name",o));e[o]===r||(i&&(_has(r,t)||_hide(r,t,e[o]?""+e[o]:n.join(o+""))),e===_global?e[o]=r:a?e[o]?e[o]=r:_hide(e,o,r):(delete e[o],_hide(e,o,r)))})(Function.prototype,o,function(){return"function"==typeof this&&this[t]||r.call(this)})}),PROTOTYPE="prototype",$export=function(e,t,o){var r,n,a,i,l=e&$export.F,c=e&$export.G,s=e&$export.S,d=e&$export.P,p=e&$export.B,h=c?_global:s?_global[t]||(_global[t]={}):(_global[t]||{})[PROTOTYPE],u=c?_core:_core[t]||(_core[t]={}),y=u[PROTOTYPE]||(u[PROTOTYPE]={});for(r in c&&(o=t),o)n=!l&&h&&void 0!==h[r],a=(n?h:o)[r],i=p&&n?_ctx(a,_global):d&&"function"==typeof a?_ctx(Function.call,a):a,h&&_redefine(h,r,a,e&$export.U),u[r]!=a&&_hide(u,r,i),d&&y[r]!=a&&(y[r]=a)};_global.core=_core,$export.F=1,$export.G=2,$export.S=4,$export.P=8,$export.B=16,$export.W=32,$export.U=64,$export.R=128;// real proto method for `library`
var defer,channel,port,_export=$export,_anInstance=function(e,t,o,r){if(!(e instanceof t)||r!==void 0&&r in e)throw TypeError(o+": incorrect invocation!");return e},_iterCall=function(t,e,o,r){try{return r?e(_anObject(o)[0],o[1]):e(o);// 7.4.6 IteratorClose(iterator, completion)
}catch(o){var n=t["return"];throw void 0!==n&&_anObject(n.call(t)),o}},_iterators={},ITERATOR=_wks("iterator"),ArrayProto=Array.prototype,_isArrayIter=function(e){return e!==void 0&&(_iterators.Array===e||ArrayProto[ITERATOR]===e)},ceil=Math.ceil,floor=Math.floor,_toInteger=function(e){return isNaN(e=+e)?0:(0<e?floor:ceil)(e)},min=Math.min,_toLength=function(e){return 0<e?min(_toInteger(e),9007199254740991):0;// pow(2, 53) - 1 == 9007199254740991
},ITERATOR$1=_wks("iterator"),core_getIteratorMethod=_core.getIteratorMethod=function(e){if(e!=null)return e[ITERATOR$1]||e["@@iterator"]||_iterators[_classof(e)]},_forOf=createCommonjsModule(function(e){var t={},o={},r=e.exports=function(e,r,n,a,i){var l,c,s,d,p=i?function(){return e}:core_getIteratorMethod(e),h=_ctx(n,a,r?2:1),u=0;if("function"!=typeof p)throw TypeError(e+" is not iterable!");// fast case for arrays with default iterator
if(_isArrayIter(p)){for(l=_toLength(e.length);l>u;u++)if(d=r?h(_anObject(c=e[u])[0],c[1]):h(e[u]),d===t||d===o)return d;}else for(s=p.call(e);!(c=s.next()).done;)if(d=_iterCall(s,h,c.value,r),d===t||d===o)return d};r.BREAK=t,r.RETURN=o}),SPECIES=_wks("species"),_speciesConstructor=function(e,t){var o,r=_anObject(e).constructor;return r===void 0||(o=_anObject(r)[SPECIES])==null?t:_aFunction(o)},_invoke=function(e,t,o){var r=o===void 0;switch(t.length){case 0:return r?e():e.call(o);case 1:return r?e(t[0]):e.call(o,t[0]);case 2:return r?e(t[0],t[1]):e.call(o,t[0],t[1]);case 3:return r?e(t[0],t[1],t[2]):e.call(o,t[0],t[1],t[2]);case 4:return r?e(t[0],t[1],t[2],t[3]):e.call(o,t[0],t[1],t[2],t[3]);}return e.apply(o,t)},document$2=_global.document,_html=document$2&&document$2.documentElement,process=_global.process,setTask=_global.setImmediate,clearTask=_global.clearImmediate,MessageChannel=_global.MessageChannel,Dispatch=_global.Dispatch,counter=0,queue={},ONREADYSTATECHANGE="onreadystatechange",run=function(){var e=+this;// eslint-disable-next-line no-prototype-builtins
if(queue.hasOwnProperty(e)){var t=queue[e];delete queue[e],t()}},listener=function(e){run.call(e.data)};setTask&&clearTask||(setTask=function(e){for(var t=[],o=1;arguments.length>o;)t.push(arguments[o++]);return queue[++counter]=function(){_invoke("function"==typeof e?e:Function(e),t)},defer(counter),counter},clearTask=function(e){delete queue[e]},"process"==_cof(process)?defer=function(e){process.nextTick(_ctx(run,e,1))}:Dispatch&&Dispatch.now?defer=function(e){Dispatch.now(_ctx(run,e,1))}:MessageChannel?(channel=new MessageChannel,port=channel.port2,channel.port1.onmessage=listener,defer=_ctx(port.postMessage,port,1)):_global.addEventListener&&"function"==typeof postMessage&&!_global.importScripts?(defer=function(e){_global.postMessage(e+"","*")},_global.addEventListener("message",listener,!1)):ONREADYSTATECHANGE in _domCreate("script")?defer=function(e){_html.appendChild(_domCreate("script"))[ONREADYSTATECHANGE]=function(){_html.removeChild(this),run.call(e)}}:defer=function(e){setTimeout(_ctx(run,e,1),0)});var _task={set:setTask,clear:clearTask},macrotask=_task.set,Observer=_global.MutationObserver||_global.WebKitMutationObserver,process$1=_global.process,Promise$1=_global.Promise,isNode="process"==_cof(process$1),_microtask=function(){var t,o,r,e=function(){var e,n;for(isNode&&(e=process$1.domain)&&e.exit();t;){n=t.fn,t=t.next;try{n()}catch(n){throw t?r():o=void 0,n}}o=void 0,e&&e.enter()};// Node.js
if(isNode)r=function(){process$1.nextTick(e)};else if(Observer&&!(_global.navigator&&_global.navigator.standalone)){var n=!0,a=document.createTextNode("");new Observer(e).observe(a,{characterData:!0}),r=function(){a.data=n=!n}}else if(Promise$1&&Promise$1.resolve){// Promise.resolve without an argument throws an error in LG WebOS 2
var i=Promise$1.resolve(void 0);r=function(){i.then(e)}}else r=function(){macrotask.call(_global,e)};return function(e){var n={fn:e,next:void 0};o&&(o.next=n),t||(t=n,r()),o=n}};// 25.4.1.5 NewPromiseCapability(C)
function PromiseCapability(e){var t,o;this.promise=new e(function(e,r){if(t!==void 0||o!==void 0)throw TypeError("Bad Promise constructor");t=e,o=r}),this.resolve=_aFunction(t),this.reject=_aFunction(o)}var f$1=function(e){return new PromiseCapability(e)},_newPromiseCapability={f:f$1},_perform=function(e){try{return{e:!1,v:e()}}catch(t){return{e:!0,v:t}}},navigator=_global.navigator,_userAgent=navigator&&navigator.userAgent||"",_promiseResolve=function(e,t){if(_anObject(e),_isObject(t)&&t.constructor===e)return t;var o=_newPromiseCapability.f(e),r=o.resolve;return r(t),o.promise},_redefineAll=function(e,t,o){for(var r in t)_redefine(e,r,t[r],o);return e},def=_objectDp.f,TAG$1=_wks("toStringTag"),_setToStringTag=function(e,t,o){e&&!_has(e=o?e:e.prototype,TAG$1)&&def(e,TAG$1,{configurable:!0,value:t})},SPECIES$1=_wks("species"),_setSpecies=function(e){var t=_global[e];_descriptors&&t&&!t[SPECIES$1]&&_objectDp.f(t,SPECIES$1,{configurable:!0,get:function(){return this}})},ITERATOR$2=_wks("iterator"),SAFE_CLOSING=!1;try{var riter=[7][ITERATOR$2]();riter["return"]=function(){SAFE_CLOSING=!0}}catch(t){/* empty */}var Internal,newGenericPromiseCapability,OwnPromiseCapability,Wrapper,_iterDetect=function(e,t){if(!t&&!SAFE_CLOSING)return!1;var o=!1;try{var r=[7],n=r[ITERATOR$2]();n.next=function(){return{done:o=!0}},r[ITERATOR$2]=function(){return n},e(r)}catch(t){/* empty */}return o},task=_task.set,microtask=_microtask(),PROMISE="Promise",TypeError$1=_global.TypeError,process$2=_global.process,versions=process$2&&process$2.versions,v8=versions&&versions.v8||"",$Promise=_global[PROMISE],isNode$1="process"==_classof(process$2),empty=function(){/* empty */},newPromiseCapability=newGenericPromiseCapability=_newPromiseCapability.f,USE_NATIVE=!!function(){try{// correct subclassing with @@species support
var e=$Promise.resolve(1),t=(e.constructor={})[_wks("species")]=function(e){e(empty,empty)};// unhandled rejections tracking support, NodeJS Promise without it fails @@species test
return(isNode$1||"function"==typeof PromiseRejectionEvent)&&e.then(empty)instanceof t// v8 6.6 (Node 10 and Chrome 66) have a bug with resolving custom thenables
// https://bugs.chromium.org/p/chromium/issues/detail?id=830565
// we can't detect it synchronously, so just check versions
&&0!==v8.indexOf("6.6")&&-1===_userAgent.indexOf("Chrome/66")}catch(t){/* empty */}}(),isThenable=function(e){var t;return!!(_isObject(e)&&"function"==typeof(t=e.then))&&t},notify=function(e,t){if(!e._n){e._n=!0;var o=e._c;microtask(function(){for(var r=e._v,n=1==e._s,a=0,l=function(t){var o,a,i,l=n?t.ok:t.fail,c=t.resolve,s=t.reject,d=t.domain;try{l?(!n&&(2==e._h&&onHandleUnhandled(e),e._h=1),!0===l?o=r:(d&&d.enter(),o=l(r),d&&(d.exit(),i=!0)),o===t.promise?s(TypeError$1("Promise-chain cycle")):(a=isThenable(o))?a.call(o,c,s):c(o)):s(r)}catch(t){d&&!i&&d.exit(),s(t)}};o.length>a;)l(o[a++]);// variable length - can't use forEach
e._c=[],e._n=!1,t&&!e._h&&onUnhandled(e)})}},onUnhandled=function(e){task.call(_global,function(){var t,o,r,n=e._v,a=isUnhandled(e);if(a&&(t=_perform(function(){isNode$1?process$2.emit("unhandledRejection",n,e):(o=_global.onunhandledrejection)?o({promise:e,reason:n}):(r=_global.console)&&r.error&&r.error("Unhandled promise rejection",n)}),e._h=isNode$1||isUnhandled(e)?2:1),e._a=void 0,a&&t.e)throw t.v})},isUnhandled=function(e){return 1!==e._h&&0===(e._a||e._c).length},onHandleUnhandled=function(e){task.call(_global,function(){var t;isNode$1?process$2.emit("rejectionHandled",e):(t=_global.onrejectionhandled)&&t({promise:e,reason:e._v})})},$reject=function(e){var t=this;t._d||(t._d=!0,t=t._w||t,t._v=e,t._s=2,!t._a&&(t._a=t._c.slice()),notify(t,!0))},$resolve=function(e){var t,o=this;if(!o._d){o._d=!0,o=o._w||o;// unwrap
try{if(o===e)throw TypeError$1("Promise can't be resolved itself");(t=isThenable(e))?microtask(function(){var r={_w:o,_d:!1};// wrap
try{t.call(e,_ctx($resolve,r,1),_ctx($reject,r,1))}catch(t){$reject.call(r,t)}}):(o._v=e,o._s=1,notify(o,!1))}catch(t){$reject.call({_w:o,_d:!1},t)}}};USE_NATIVE||($Promise=function(e){_anInstance(this,$Promise,PROMISE,"_h"),_aFunction(e),Internal.call(this);try{e(_ctx($resolve,this,1),_ctx($reject,this,1))}catch(e){$reject.call(this,e)}},Internal=function(){this._c=[],this._a=void 0,this._s=0,this._d=!1,this._v=void 0,this._h=0,this._n=!1},Internal.prototype=_redefineAll($Promise.prototype,{// 25.4.5.3 Promise.prototype.then(onFulfilled, onRejected)
then:function(e,t){var o=newPromiseCapability(_speciesConstructor(this,$Promise));return o.ok="function"!=typeof e||e,o.fail="function"==typeof t&&t,o.domain=isNode$1?process$2.domain:void 0,this._c.push(o),this._a&&this._a.push(o),this._s&&notify(this,!1),o.promise},// 25.4.5.1 Promise.prototype.catch(onRejected)
catch:function(e){return this.then(void 0,e)}}),OwnPromiseCapability=function(){var e=new Internal;this.promise=e,this.resolve=_ctx($resolve,e,1),this.reject=_ctx($reject,e,1)},_newPromiseCapability.f=newPromiseCapability=function(e){return e===$Promise||e===Wrapper?new OwnPromiseCapability(e):newGenericPromiseCapability(e)}),_export(_export.G+_export.W+_export.F*!USE_NATIVE,{Promise:$Promise}),_setToStringTag($Promise,PROMISE),_setSpecies(PROMISE),Wrapper=_core[PROMISE],_export(_export.S+_export.F*!USE_NATIVE,PROMISE,{// 25.4.4.5 Promise.reject(r)
reject:function(e){var t=newPromiseCapability(this),o=t.reject;return o(e),t.promise}}),_export(_export.S+_export.F*!USE_NATIVE,PROMISE,{// 25.4.4.6 Promise.resolve(x)
resolve:function(e){return _promiseResolve(this,e)}}),_export(_export.S+_export.F*!(USE_NATIVE&&_iterDetect(function(e){$Promise.all(e)["catch"](empty)})),PROMISE,{// 25.4.4.1 Promise.all(iterable)
all:function(e){var t=this,o=newPromiseCapability(t),r=o.resolve,n=o.reject,a=_perform(function(){var o=[],a=0,i=1;_forOf(e,!1,function(e){var l=a++,c=!1;o.push(void 0),i++,t.resolve(e).then(function(e){c||(c=!0,o[l]=e,--i||r(o))},n)}),--i||r(o)});return a.e&&n(a.v),o.promise},// 25.4.4.4 Promise.race(iterable)
race:function(e){var t=this,o=newPromiseCapability(t),r=o.reject,n=_perform(function(){_forOf(e,!1,function(e){t.resolve(e).then(o.resolve,r)})});return n.e&&r(n.v),o.promise}});var runtime=createCommonjsModule(function(e){!function(t){function o(e,t,o,r){// If outerFn provided and outerFn.prototype is a Generator, then outerFn.prototype instanceof Generator.
var a=t&&t.prototype instanceof n?t:n,i=Object.create(a.prototype),l=new u(r||[]);return i._invoke=s(e,o,l),i}// Try/catch helper to minimize deoptimizations. Returns a completion
// record like context.tryEntries[i].completion. This interface could
// have been (and was previously) designed to take a closure to be
// invoked without arguments, but in all the cases we care about we
// already have an existing method we want to call, so there's no need
// to create a new function object. We can even get away with assuming
// the method takes exactly one argument, since that happens to be true
// in every case, so we don't have to touch the arguments object. The
// only additional allocation required is the completion record, which
// has a stable shape and so hopefully should be cheap to allocate.
function r(e,t,o){try{return{type:"normal",arg:e.call(t,o)}}catch(e){return{type:"throw",arg:e}}}// Dummy constructor functions that we use as the .constructor and
// .constructor.prototype properties for functions that return Generator
// objects. For full spec compliance, you may wish to configure your
// minifier not to mangle the names of these two functions.
function n(){}function a(){}function i(){}// This is a polyfill for %IteratorPrototype% for environments that
// don't natively support it.
// Helper for defining the .next, .throw, and .return methods of the
// Iterator interface in terms of a single ._invoke method.
function l(e){["next","throw","return"].forEach(function(t){e[t]=function(e){return this._invoke(t,e)}})}function c(e){function t(o,n,a,i){var l=r(e[o],e,n);if("throw"===l.type)i(l.arg);else{var c=l.arg,s=c.value;return s&&"object"==typeof s&&f.call(s,"__await")?Promise.resolve(s.__await).then(function(e){t("next",e,a,i)},function(e){t("throw",e,a,i)}):Promise.resolve(s).then(function(e){c.value=e,a(c)},i)}}function o(e,o){function r(){return new Promise(function(r,n){t(e,o,r,n)})}return n=// If enqueue has been called before, then we want to wait until
// all previous Promises have been resolved before calling invoke,
// so that results are always delivered in the correct order. If
// enqueue has not been called before, then it is important to
// call invoke immediately, without waiting on a callback to fire,
// so that the async generator function has the opportunity to do
// any necessary setup in a predictable way. This predictability
// is why the Promise constructor synchronously invokes its
// executor callback, and why async functions synchronously
// execute code before the first await. Since we implement simple
// async functions in terms of async generators, it is especially
// important to get this right, even though it requires care.
n?n.then(r,// Avoid propagating failures to Promises returned by later
// invocations of the iterator.
r):r()}// Define the unified helper method that is used to implement .next,
// .throw, and .return (see defineIteratorMethods).
var n;this._invoke=o}function s(e,t,o){var n="suspendedStart";return function(a,i){if(n==="executing")throw new Error("Generator is already running");if("completed"===n){if("throw"===a)throw i;// Be forgiving, per 25.3.3.3.3 of the spec:
// https://people.mozilla.org/~jorendorff/es6-draft.html#sec-generatorresume
return g()}for(o.method=a,o.arg=i;;){var l=o.delegate;if(l){var c=d(l,o);if(c){if(c===E)continue;return c}}if("next"===o.method)o.sent=o._sent=o.arg;else if("throw"===o.method){if("suspendedStart"===n)throw n="completed",o.arg;o.dispatchException(o.arg)}else"return"===o.method&&o.abrupt("return",o.arg);n="executing";var s=r(e,t,o);if("normal"===s.type){if(n=o.done?"completed":"suspendedYield",s.arg===E)continue;return{value:s.arg,done:o.done}}"throw"===s.type&&(n="completed",o.method="throw",o.arg=s.arg)}}}// Call delegate.iterator[context.method](context.arg) and handle the
// result, either by returning a { value, done } result from the
// delegate iterator, or by modifying context.method and context.arg,
// setting context.delegate to null, and returning the ContinueSentinel.
function d(e,t){var o=e.iterator[t.method];if(void 0===o){if(t.delegate=null,"throw"===t.method){if(e.iterator.return&&(t.method="return",t.arg=void 0,d(e,t),"throw"===t.method))// If maybeInvokeDelegate(context) changed context.method from
// "return" to "throw", let that override the TypeError below.
return E;t.method="throw",t.arg=new TypeError("The iterator does not provide a 'throw' method")}return E}var n=r(o,e.iterator,t.arg);if("throw"===n.type)return t.method="throw",t.arg=n.arg,t.delegate=null,E;var a=n.arg;if(!a)return t.method="throw",t.arg=new TypeError("iterator result is not an object"),t.delegate=null,E;if(a.done)t[e.resultName]=a.value,t.next=e.nextLoc,"return"!==t.method&&(t.method="next",t.arg=void 0);else// Re-yield the result returned by the delegate method.
return a;// The delegate iterator is finished, so forget it and continue with
// the outer generator.
return t.delegate=null,E}// Define Generator.prototype.{next,throw,return} in terms of the
// unified ._invoke helper method.
function p(e){var t={tryLoc:e[0]};1 in e&&(t.catchLoc=e[1]),2 in e&&(t.finallyLoc=e[2],t.afterLoc=e[3]),this.tryEntries.push(t)}function h(e){var t=e.completion||{};t.type="normal",delete t.arg,e.completion=t}function u(e){this.tryEntries=[{tryLoc:"root"}],e.forEach(p,this),this.reset(!0)}function y(e){if(e){var t=e[x];if(t)return t.call(e);if("function"==typeof e.next)return e;if(!isNaN(e.length)){var o=-1,r=function t(){for(;++o<e.length;)if(f.call(e,o))return t.value=e[o],t.done=!1,t;return t.value=void 0,t.done=!0,t};return r.next=r}}// Return an iterator with no values.
return{next:g}}function g(){return{value:void 0,done:!0}}var m=Object.prototype,f=m.hasOwnProperty,v="function"==typeof Symbol?Symbol:{},x=v.iterator||"@@iterator",_=v.asyncIterator||"@@asyncIterator",w=v.toStringTag||"@@toStringTag",b=t.regeneratorRuntime;if(b)// Don't bother evaluating the rest of this file if the runtime was
// already defined globally.
return void(e.exports=b);// Define the runtime globally (as expected by generated code) as either
// module.exports (if we're in a module) or a new, empty object.
b=t.regeneratorRuntime=e.exports,b.wrap=o;var E={},k={};k[x]=function(){return this};var S=Object.getPrototypeOf,O=S&&S(S(y([])));O&&O!==m&&f.call(O,x)&&(k=O);var P=i.prototype=n.prototype=Object.create(k);a.prototype=P.constructor=i,i.constructor=a,i[w]=a.displayName="GeneratorFunction",b.isGeneratorFunction=function(e){var t="function"==typeof e&&e.constructor;return!!t&&(t===a||// For the native GeneratorFunction constructor, the best we can
// do is to check its .name property.
"GeneratorFunction"===(t.displayName||t.name))},b.mark=function(e){return Object.setPrototypeOf?Object.setPrototypeOf(e,i):(e.__proto__=i,!(w in e)&&(e[w]="GeneratorFunction")),e.prototype=Object.create(P),e},b.awrap=function(e){return{__await:e}},l(c.prototype),c.prototype[_]=function(){return this},b.AsyncIterator=c,b.async=function(e,t,r,n){var a=new c(o(e,t,r,n));return b.isGeneratorFunction(t)?a// If outerFn is a generator, return the full iterator.
:a.next().then(function(e){return e.done?e.value:a.next()})},l(P),P[w]="Generator",P[x]=function(){return this},P.toString=function(){return"[object Generator]"},b.keys=function(e){var t=[];for(var o in e)t.push(o);// Rather than returning an object with a next method, we keep
// things simple and return the next function itself.
return t.reverse(),function o(){for(;t.length;){var r=t.pop();if(r in e)return o.value=r,o.done=!1,o}// To avoid creating an additional object, we just hang the .value
// and .done properties off the next function object itself. This
// also ensures that the minifier will not anonymize the function.
return o.done=!0,o}},b.values=y,u.prototype={constructor:u,reset:function(e){if(this.prev=0,this.next=0,this.sent=this._sent=void 0,this.done=!1,this.delegate=null,this.method="next",this.arg=void 0,this.tryEntries.forEach(h),!e)for(var t in this)// Not sure about the optimal order of these conditions:
"t"===t.charAt(0)&&f.call(this,t)&&!isNaN(+t.slice(1))&&(this[t]=void 0)},stop:function(){this.done=!0;var e=this.tryEntries[0],t=e.completion;if("throw"===t.type)throw t.arg;return this.rval},dispatchException:function(e){function t(t,r){return a.type="throw",a.arg=e,o.next=t,r&&(o.method="next",o.arg=void 0),!!r}if(this.done)throw e;for(var o=this,r=this.tryEntries.length-1;0<=r;--r){var n=this.tryEntries[r],a=n.completion;if("root"===n.tryLoc)// Exception thrown outside of any try block that could handle
// it, so set the completion value of the entire function to
// throw the exception.
return t("end");if(n.tryLoc<=this.prev){var l=f.call(n,"catchLoc"),c=f.call(n,"finallyLoc");if(l&&c){if(this.prev<n.catchLoc)return t(n.catchLoc,!0);if(this.prev<n.finallyLoc)return t(n.finallyLoc)}else if(l){if(this.prev<n.catchLoc)return t(n.catchLoc,!0);}else if(!c)throw new Error("try statement without catch or finally");else if(this.prev<n.finallyLoc)return t(n.finallyLoc)}}},abrupt:function(e,t){for(var o,r=this.tryEntries.length-1;0<=r;--r)if(o=this.tryEntries[r],o.tryLoc<=this.prev&&f.call(o,"finallyLoc")&&this.prev<o.finallyLoc){var n=o;break}n&&("break"===e||"continue"===e)&&n.tryLoc<=t&&t<=n.finallyLoc&&(n=null);var a=n?n.completion:{};return a.type=e,a.arg=t,n?(this.method="next",this.next=n.finallyLoc,E):this.complete(a)},complete:function(e,t){if("throw"===e.type)throw e.arg;return"break"===e.type||"continue"===e.type?this.next=e.arg:"return"===e.type?(this.rval=this.arg=e.arg,this.method="return",this.next="end"):"normal"===e.type&&t&&(this.next=t),E},finish:function(e){for(var t,o=this.tryEntries.length-1;0<=o;--o)if(t=this.tryEntries[o],t.finallyLoc===e)return this.complete(t.completion,t.afterLoc),h(t),E},catch:function(e){for(var t,o=this.tryEntries.length-1;0<=o;--o)if(t=this.tryEntries[o],t.tryLoc===e){var r=t.completion;if("throw"===r.type){var n=r.arg;h(t)}return n}// The context.catch method must only be called with a location
// argument that corresponds to a known catch block.
throw new Error("illegal catch attempt")},delegateYield:function(e,t,o){return this.delegate={iterator:y(e),resultName:t,nextLoc:o},"next"===this.method&&(this.arg=void 0),E}}}(// In sloppy mode, unbound `this` refers to the global object, fallback to
// Function constructor if we're in global strict mode. That is sadly a form
// of indirect eval which violates Content Security Policy.
function(){return this}()||Function("return this")())});function asyncGeneratorStep(e,t,o,r,n,a,i){try{var l=e[a](i),c=l.value}catch(e){return void o(e)}l.done?t(c):Promise.resolve(c).then(r,n)}function _asyncToGenerator(e){return function(){var t=this,o=arguments;return new Promise(function(r,n){function a(e){asyncGeneratorStep(l,r,n,a,i,"next",e)}function i(e){asyncGeneratorStep(l,r,n,a,i,"throw",e)}var l=e.apply(t,o);a(void 0)})}}function _classCallCheck(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}function _defineProperties(e,t){for(var o,r=0;r<t.length;r++)o=t[r],o.enumerable=o.enumerable||!1,o.configurable=!0,"value"in o&&(o.writable=!0),Object.defineProperty(e,o.key,o)}function _createClass(e,t,o){return t&&_defineProperties(e.prototype,t),o&&_defineProperties(e,o),e}function _defineProperty(e,t,o){return t in e?Object.defineProperty(e,t,{value:o,enumerable:!0,configurable:!0,writable:!0}):e[t]=o,e}function _objectSpread(e){for(var t=1;t<arguments.length;t++){var o=null==arguments[t]?{}:arguments[t],r=Object.keys(o);"function"==typeof Object.getOwnPropertySymbols&&(r=r.concat(Object.getOwnPropertySymbols(o).filter(function(e){return Object.getOwnPropertyDescriptor(o,e).enumerable}))),r.forEach(function(t){_defineProperty(e,t,o[t])})}return e}// 7.2.1 RequireObjectCoercible(argument)
var _defined=function(e){if(e==null)throw TypeError("Can't call method on  "+e);return e},_toObject=function(e){return Object(_defined(e))},_strictMethod=function(e,t){return!!e&&_fails(function(){t?e.call(null,function(){/* empty */},1):e.call(null)})},$sort=[].sort,test=[1,2,3];// 7.1.13 ToObject(argument)
_export(_export.P+_export.F*(_fails(function(){test.sort(void 0)})||!_fails(function(){test.sort(null)})||!_strictMethod($sort)),"Array",{// 22.1.3.25 Array.prototype.sort(comparefn)
sort:function(e){return e===void 0?$sort.call(_toObject(this)):$sort.call(_toObject(this),_aFunction(e))}});var _fixReWks=function(e,t,o){var r=_wks(e),n=o(_defined,r,""[e]),a=n[0],i=n[1];_fails(function(){var t={};return t[r]=function(){return 7},7!=""[e](t)})&&(_redefine(String.prototype,e,a),_hide(RegExp.prototype,r,2==t// 21.2.5.8 RegExp.prototype[@@replace](string, replaceValue)
// 21.2.5.11 RegExp.prototype[@@split](string, limit)
?function(e,t){return i.call(e,this,t)}// 21.2.5.6 RegExp.prototype[@@match](string)
// 21.2.5.9 RegExp.prototype[@@search](string)
:function(e){return i.call(e,this)}))};// @@replace logic
_fixReWks("replace",2,function(e,t,o){// 21.1.3.14 String.prototype.replace(searchValue, replaceValue)
return[function(r,n){var a=e(this),i=r==null?void 0:r[t];return i===void 0?o.call(a+"",r,n):i.call(r,a,n)},o]});var f$2={}.propertyIsEnumerable,_objectPie={f:f$2},_iobject=Object("z").propertyIsEnumerable(0)?Object:function(e){return"String"==_cof(e)?e.split(""):Object(e)},_toIobject=function(e){return _iobject(_defined(e))},gOPD=Object.getOwnPropertyDescriptor,f$3=_descriptors?gOPD:function(e,t){if(e=_toIobject(e),t=_toPrimitive(t,!0),_ie8DomDefine)try{return gOPD(e,t)}catch(t){/* empty */}return _has(e,t)?_propertyDesc(!_objectPie.f.call(e,t),e[t]):void 0},_objectGopd={f:f$3},check=function(e,t){if(_anObject(e),!_isObject(t)&&null!==t)throw TypeError(t+": can't set as prototype!")},_setProto={set:Object.setPrototypeOf||("__proto__"in{}?// eslint-disable-line
function(e,t,o){try{o=_ctx(Function.call,_objectGopd.f(Object.prototype,"__proto__").set,2),o(e,[]),t=!(e instanceof Array)}catch(o){t=!0}return function(e,r){return check(e,r),t?e.__proto__=r:o(e,r),e}}({},!1):void 0),check:check},setPrototypeOf=_setProto.set,_inheritIfRequired=function(e,t,o){var r,n=t.constructor;return n!==o&&"function"==typeof n&&(r=n.prototype)!==o.prototype&&_isObject(r)&&setPrototypeOf&&setPrototypeOf(e,r),e},max=Math.max,min$1=Math.min,_toAbsoluteIndex=function(e,t){return e=_toInteger(e),0>e?max(e+t,0):min$1(e,t)},_arrayIncludes=function(e){return function(t,o,r){var n,a=_toIobject(t),i=_toLength(a.length),l=_toAbsoluteIndex(r,i);// Array#includes uses SameValueZero equality algorithm
// eslint-disable-next-line no-self-compare
if(e&&o!=o){for(;i>l;)// eslint-disable-next-line no-self-compare
if(n=a[l++],n!=n)return!0;// Array#indexOf ignores holes, Array#includes - not
}else for(;i>l;l++)if((e||l in a)&&a[l]===o)return e||l||0;return!e&&-1}},shared=_shared("keys"),_sharedKey=function(e){return shared[e]||(shared[e]=_uid(e))},arrayIndexOf=_arrayIncludes(!1),IE_PROTO=_sharedKey("IE_PROTO"),_objectKeysInternal=function(e,t){var o,r=_toIobject(e),n=0,a=[];for(o in r)o!=IE_PROTO&&_has(r,o)&&a.push(o);// Don't enum bug & hidden keys
for(;t.length>n;)_has(r,o=t[n++])&&(~arrayIndexOf(a,o)||a.push(o));return a},_enumBugKeys=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"],hiddenKeys=_enumBugKeys.concat("length","prototype"),f$4=Object.getOwnPropertyNames||function(e){return _objectKeysInternal(e,hiddenKeys)},_objectGopn={f:f$4},MATCH=_wks("match"),_isRegexp=function(e){var t;return _isObject(e)&&((t=e[MATCH])===void 0?"RegExp"==_cof(e):!!t)},_flags=function(){var e=_anObject(this),t="";return e.global&&(t+="g"),e.ignoreCase&&(t+="i"),e.multiline&&(t+="m"),e.unicode&&(t+="u"),e.sticky&&(t+="y"),t},dP$1=_objectDp.f,gOPN=_objectGopn.f,$RegExp=_global.RegExp,Base=$RegExp,proto=$RegExp.prototype,re1=/a/g,re2=/a/g,CORRECT_NEW=new $RegExp(re1)!==re1;if(_descriptors&&(!CORRECT_NEW||_fails(function(){// RegExp constructor can alter flags and IsRegExp works correct with @@match
return re2[_wks("match")]=!1,$RegExp(re1)!=re1||$RegExp(re2)==re2||"/a/i"!=$RegExp(re1,"i")}))){$RegExp=function(e,t){var o=this instanceof $RegExp,r=_isRegexp(e),n=t===void 0;return!o&&r&&e.constructor===$RegExp&&n?e:_inheritIfRequired(CORRECT_NEW?new Base(r&&!n?e.source:e,t):Base((r=e instanceof $RegExp)?e.source:e,r&&n?_flags.call(e):t),o?this:proto,$RegExp)};for(var proxy=function(e){(e in $RegExp)||dP$1($RegExp,e,{configurable:!0,get:function(){return Base[e]},set:function(t){Base[e]=t}})},keys=gOPN(Base),i=0;keys.length>i;)proxy(keys[i++]);proto.constructor=$RegExp,$RegExp.prototype=proto,_redefine(_global,"RegExp",$RegExp)}_setSpecies("RegExp");var fromCharCode=String.fromCharCode,$fromCodePoint=String.fromCodePoint;_export(_export.S+_export.F*(!!$fromCodePoint&&1!=$fromCodePoint.length),"String",{// 21.1.2.2 String.fromCodePoint(...codePoints)
fromCodePoint:function(){// eslint-disable-line no-unused-vars
for(var e,t=[],o=arguments.length,r=0;o>r;){if(e=+arguments[r++],_toAbsoluteIndex(e,1114111)!==e)throw RangeError(e+" is not a valid code point");t.push(65536>e?fromCharCode(e):fromCharCode(((e-=65536)>>10)+55296,e%1024+56320))}return t.join("")}});// export function sortBy(elements, type) {
//   elements.sort((left, right) => {
//     return (left[type] |)
//   })
// }
function autoTransformCamel(e){var t=camelTransformToLink(e);return t?camelTransformToLink(e):linkTransformToCamel(e)}function camelTransformToLink(e){var t=/([A-Z])/g;return!!t.test(e)&&e.replace(t,"-".concat(String.fromCodePoint(RegExp.$1.charCodeAt(0)+32)))}function linkTransformToCamel(e){var t=/-([a-z])/g;return!!t.test(e)&&e.replace(t,String.fromCodePoint(RegExp.$1.charCodeAt(0)-32))}var ElementUtil=/*#__PURE__*/function(){function e(t){// single case
return _classCallCheck(this,e),this.instance?this.instance:void(this.radio=t.radio,this.crossOrigin=t.crossOrigin,this.ctx=t.ctx,this.canvas=t.canvas,this.zIndexMax=0);// the browser's dpi.
}/**
   * @desc transform actual pixels to canvas unit
   *
   * @param {string} pixels actual pixels
   * @return unit in canvas
   * @memberof Canvas
   */return _createClass(e,[{key:"normalizeUnit",value:function(e){return e+="",-1<e.indexOf("px")&&(e=e.replace("px","")),e*this.radio}/**
     * @desc the major is sorting the elements by zIndex
     *
     * @param {Array} elements
     * @memberof Canvas
     */},{key:"sortByCSSProperty",value:function(e,t){var o=this;e.sort(function(e,r){return o.zIndexMax=e[t||autoTransformCamel(t)]>o.zIndexMax?e[t||autoTransformCamel(t)]:o.zIndexMax,e[t]||e[autoTransformCamel(t)||0]-(r[t]||r[autoTransformCamel(t)]||0)})}/**
     * @desc deal with text
     * @param {Object} item={}
     * @memberof Canvas
     * @return {Promise}
     */},{key:"drawText",value:function(){var e=this,t=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};if(!(t instanceof Object))throw"the configuration of the text if not an object";var o=this.normalizeUnit.bind(this),r=t.left?o(t.left):t.right?this.canvas.width-o(t.right):0,n=(t.top?o(t.top):t.bottom?this.canvas.height-o(t.bottom):0)+o(t.fontSize||t["font-size"]);return new Promise(function(a){t.color?e.ctx.fillStyle=t.color:void 0,e.ctx.font=o(t.fontSize||t["font-size"])+"px "+(t.fontFamily||t["font-family"]),t.left&&t.right||t.width?e.ctx.fillText(t.text,r,n,t.width?o(t.width):e.canvas.width-o(t.left)-o(t.right)):e.ctx.fillText(t.text,r,n),a()})}/**
     * @desc deal with image
     *
     * @param {*} image={}
     * @return {Promise}
     * @memberof Canvas
     */},{key:"drawImage",value:function(){var e=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function e(){var t,o,r,n,a,i=this,l=arguments;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:if(t=0<l.length&&void 0!==l[0]?l[0]:{},t instanceof Object){e.next=3;break}throw"\u4F20\u5165\u7684\u56FE\u7247\u4E0D\u662F object";case 3:return o=document.createElement("img"),r=this.normalizeUnit.bind(this),n=!1,a=!1,o.crossOrigin=this.crossOrigin,o.src=t.src,void 0===t.width&&void 0!==t.left&&void 0!==t.right&&(n=!0,t.width=this.canvas.width-r(t.left)-r(t.right)),void 0===t.height&&void 0!==t.top&&void 0!==t.bottom&&(a=!0,t.height=this.canvas.height-r(t.top)-r(t.bottom)),e.abrupt("return",new Promise(function(e){o.onload=function(){i.ctx.drawImage(o,t.left?r(t.left):t.right?i.canvas.width-r(t.width)-r(t.right):0,t.top?r(t.top):t.bottom?i.canvas.height-r(t.height)-r(t.height):0,n?t.width:r(t.width),a?t.height:r(t.height)),e()}}));case 12:case"end":return e.stop();}},e,this)}));return function(){return e.apply(this,arguments)}}()/**
     * @desc midware to detail type
     *
     * @param {Object} element
     * @returns {Function}
     * @memberof Canvas
     */},{key:"drawElement",value:function(e){return e.src?this.drawImage(e):this.drawText(e)}}]),e}(),utilInstance=null,element2canvas=/*#__PURE__*/function(){function e(t){_classCallCheck(this,e),this.opts=null,this.ctx=null,this.canvas=null,this.defaultOptions={background:"#fff"},this.opts=_objectSpread({},this.defaultOptions,t)}/**
  * @return {Promise}
  */return _createClass(e,[{key:"init",value:function(){var e=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function e(){var t,o,r=this;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return this.canvas=document.createElement("canvas"),this.ctx=this.canvas.getContext("2d"),t=this.opts,o=document.body||document.documentElement,utilInstance=new ElementUtil({radio:window.devicePixelRatio,crossOrigin:this.opts.crossOrigin,ctx:this.ctx,canvas:this.canvas}),this.canvas.width=utilInstance.normalizeUnit(t.width),this.canvas.height=utilInstance.normalizeUnit(t.height),this.canvas.style.width=-1<t.width.indexOf("px")?t.width:t.width+"px",this.canvas.style.height=-1<t.height.indexOf("px")?t.height:t.height+"px",this.canvas.style.zIndex=t.zIndex||t["z-index"]||1,t.container?document.querySelector(t.container).appendChild(this.canvas):o.appendChild(this.canvas),-1<t.background.indexOf("/")||-1<t.background.indexOf(".")?utilInstance.drawImage({src:t.background,left:0,top:0,right:0,bottom:0}):(this.ctx.fillStyle=t.background,this.ctx.fillRect(0,0,this.canvas.width,this.canvas.height)),utilInstance.sortByCSSProperty(t.elements),e.abrupt("return",new Promise(/*#__PURE__*/function(){var e=_asyncToGenerator(/*#__PURE__*/regeneratorRuntime.mark(function e(o){var n;return regeneratorRuntime.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:t.elements=t.elements||[],n=0;case 2:if(!(n<t.elements.length)){e.next=8;break}return e.next=5,utilInstance.drawElement(t.elements[n]);case 5:n++,e.next=2;break;case 8:o(r.canvas);case 9:case"end":return e.stop();}},e,this)}));return function(){return e.apply(this,arguments)}}()));case 14:case"end":return e.stop();}},e,this)}));return function(){return e.apply(this,arguments)}}()/** 
     * @return img base64
     */},{key:"toDataURL",value:function(e,t){return this.canvas.toDataURL(e,t)}/**
     *
     * @desc add a element
     * @param {Object} [element={}]
     * @memberof element2canvas
     * @return {Promise}
     */},{key:"add",value:function(){var e=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};return e.zIndex=++utilInstance.zIndexMax,utilInstance.drawElement(e)}}]),e}();module.exports=element2canvas;
